In [34]:
%matplotlib inline
import numpy as np
import pandas as pd
import math
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler 
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (20.0, 10.0)

In [39]:
!mkdir data && curl -o data/train.csv -LJO https://raw.githubusercontent.com/AlinaPaiu/Tekwill-Machine-Learning-Course/main/Homework/Homeworks/Kaggle_Competition/train.csv

A subdirectory or file data already exists.


In [ ]:
data.quality.value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [34]:
#In case there are null values - replace them with mean value 
for column in data:
  mean = data[column].mean()
  data[column] = data[column].fillna(mean)

In [55]:
# Collecting X and Y
y = data['quality'].values
X = data.drop(['quality'], axis=1).values

In [56]:
X, y

(array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
        [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
        [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
        ...,
        [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
        [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
        [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]]),
 array([5, 5, 5, ..., 6, 5, 6]))

In urmatoarele celule faceti o analiza a setului de date. Vezi daca exista valori NaN, si inlocuieste-le cu media pe coloana. Incearca sa Standardizezi (sau sa Normalizezi) datele.

In [57]:
#Checking for null values (NaN) - no replacement with mean() is required
data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [59]:
#Data Normalization
mm_scaler = MinMaxScaler()
X = mm_scaler.fit_transform(X)
y = mm_scaler.fit_transform(y.reshape(-1,1))

In [60]:
#Data after normalization
X, y

(array([[0.24778761, 0.39726027, 0.        , ..., 0.60629921, 0.13772455,
         0.15384615],
        [0.28318584, 0.52054795, 0.        , ..., 0.36220472, 0.20958084,
         0.21538462],
        [0.28318584, 0.43835616, 0.04      , ..., 0.40944882, 0.19161677,
         0.21538462],
        ...,
        [0.15044248, 0.26712329, 0.13      , ..., 0.53543307, 0.25149701,
         0.4       ],
        [0.11504425, 0.35958904, 0.12      , ..., 0.65354331, 0.22754491,
         0.27692308],
        [0.12389381, 0.13013699, 0.47      , ..., 0.51181102, 0.19760479,
         0.4       ]]), array([[0.4],
        [0.4],
        [0.4],
        ...,
        [0.6],
        [0.4],
        [0.6]]))

Imparte setul de date in set de date in: date de antrenare, date pentru test, cu porportia de 0.2 pentru test.

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

Instantiaza modelul LinearRegression din modulul sklearn.linear_model. Cheama functia .fit() cu parametrii de intrare respectivi pentru a antrena modelul.

In [66]:
from sklearn.linear_model import LinearRegression

regr = LinearRegression()
regr.fit(X_train, y_train)

LinearRegression()

Verifica scorul prezicerilor tale. Incearca sa chemi functia *mean_squared_error* din modulul *sklearn.metrics* pentru a vedea eroarea dintre prezicerile tale si valoarea adevarata a targetului. Fa asta atat pentru setul de antrenare cat si cel de test.

In [70]:
from sklearn.metrics import mean_squared_error

train_score = regr.score(X_train, y_train)
print("The training score of model is: ", train_score)

test_score = regr.score(X_test, y_test)
print("The score of the model on test data is:", test_score )

The training score of model is:  0.347992619352986
The score of the model on test data is: 0.40318034127962166


In [74]:
y_pred_train = regr.predict(X_train)
mean_squared_error(y_train, y_pred_train)

0.01696764629255962

In [75]:
y_pred_test = regr.predict(X_test)
mean_squared_error(y_test, y_pred_test)

0.015601005758558212