## Tema pentru acasa: Vectori și Matrici

Implementati urmatoarele functii:

Scrie o functie care aduna doi vectori. Verifica pe un exemplu daca functia lucreaza. 
Iată formula:
\begin{equation}\vec{z} = \vec{v}+\vec{s}\end{equation}

Un exempu are fi:
\begin{equation}\vec{z} = \begin{bmatrix}2 \\ 1 \end{bmatrix} + \begin{bmatrix}-3 \\ 2 \end{bmatrix}\end{equation}

In [1]:
import numpy as np

def aduna_vectori(v1, v2):

  vector1 = np.array(v1)
  vector2 = np.array(v2)

  return vector1 + vector2

In [2]:
aduna_vectori([2,1], [-3,2])

array([-1,  3])

Scrie o functie care calculeaza magnitudinea unui vector de orice dimensiune. Verifica pe un exemplu daca functia lucreaza. 

In [3]:
def magnitudine(v):

  vector = np.array(v)

  return np.linalg.norm(vector)

In [4]:
magnitudine([2,1])

2.23606797749979

Scrie o functie care sa adune urmatoarele doua matrici:

\begin{equation}A = \begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix}\end{equation}

\begin{equation}B = \begin{bmatrix}6 & 5 & 4 \\3 & 2 & 1\end{bmatrix}\end{equation}

\begin{equation}A + B = ?\end{equation}

 Verifica pe un exemplu daca functia lucreaza. 

In [5]:
def aduna_matrici(A, B):

  A = np.array(A)
  B = np.array(B)

  return A+B

In [6]:
aduna_matrici([[1,2,3], [4,5,6]], [[6,5,4], [3,2,1]])

array([[7, 7, 7],
       [7, 7, 7]])

Scrie o functie care sa scada urmatoarele doua matrici:

\begin{equation}A = \begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix}\end{equation}

\begin{equation}B = \begin{bmatrix}6 & 5 & 4 \\3 & 2 & 1\end{bmatrix}\end{equation}

\begin{equation}A - B = ?\end{equation}

 Verifica pe un exemplu daca functia lucreaza. 

In [7]:
def scade_matrici(A, B):

  A = np.array(A)
  B = np.array(B)

  return A-B

In [8]:
scade_matrici([[1,2,3], [4,5,6]], [[6,5,4], [3,2,1]])

array([[-5, -3, -1],
       [ 1,  3,  5]])